### ISSUE TITLE
new homography config file format

### ISSUE THREAD

**Issue by fabolhak** [tum-phoenix/drive_ros_image_recognition#7]
I finished the homography tool. However config file looks a little bit different. Should be easy to implement though ([openCV standard file format](http://docs.opencv.org/2.4/modules/core/doc/xml_yaml_persistence.html#xml-yaml-file-storages-writing-to-a-file-storage)):

```
%YAML:1.0
---
world2cam: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1.6676361332715868e+02, -1.0428330379498122e+02,
       4.1597387708160539e+01, -5.2519490660059613e+00,
       -8.2307684428883232e-01, 3.0384286657407092e+01,
       2.5682926070995704e-01, 2.1500930073372294e-03,
       2.1584098198720713e-02 ]
cam2world: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9976742093947402e-05, -2.8157789591709489e-03,
       3.7711403556109269e+00, -9.5254190961238001e-03,
       8.5232402807543656e-03, 6.3593101745577494e+00,
       -2.4075204448218500e-04, 3.2655923939449022e-02,
       8.2411143302759682e-01 ]
```

**Comment by MaslinuPoimal** [comment]
Great! Will take a look at this today.

**Comment by fabolhak** [comment]
What if we add the homography config to the ximea importer package and publish a new `/camera/camera_homog` message (analogous to camera_info message), so that interested nodes can subscribe and get the parameters.

This would make more sense in my opinion, since the camera homography parameters are a camera specific entity and should therefore be stored in the camera importer package 🤔.

I guess implementation-wise this should not be a big overhead to do so.

**Comment by fabolhak** [comment]
Hey, I added a custom `drive_ros_msgs` [package](https://github.com/tum-phoenix/drive_ros_config/commit/f475903487e4db4a88c65f95b3e6cbfeea58b24f). Please add the camera homography message definition there.

**Comment by MaslinuPoimal** [comment]
As talked about yesterday, I would suggest simply using this: http://docs.ros.org/api/std_msgs/html/msg/Float32MultiArray.html.

But since we still will likely need some custom message types, we will use that package sooner or later.

**Comment by fabolhak** [comment]
homography publisher added in ximea camera importer: https://github.com/tum-phoenix/drive_ros_ximea_importer/commit/74b2d899980dfdd2cf2be71c61e3d155b4bdb93d

imaging adaptation still missing (@MaslinuPoimal will take care): https://github.com/tum-phoenix/drive_ros_image_recognition/blob/WIP/include/drive_ros_image_recognition/common_image_operations.h#L45

**Comment by fabolhak** [comment]
fixed in: https://github.com/tum-phoenix/drive_ros_image_recognition/commit/ce001cd13413ad4fae2a69302a66cd0445574db1
